### ISSUE TITLE
README

### ISSUE THREAD

**Issue by bezebee** [bezebee/star-wars-hackathon#35]
Teams:
- Developers
- Design
- Documentation
- Audio

Consider Cloudinary to use to link images

- README  [Template](https://github.com/andrewdempsey2018/Readme-Template-SWHack-May-23)

Headings:

- Design
- Wireframes
- Testing
- Development and Deployment
- Resources and tutorials

T[here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) are few README cheatsheets. One example being here, but use your preferred one.

**Comment by AlexaH88** [comment]
Teams:
- Developers
- Design
- Documentation
- Audio

Consider Cloudinary to use to link images

- README  [Template](https://github.com/andrewdempsey2018/Readme-Template-SWHack-May-23)

Headings:

- Design
- Wireframes
- Testing
- Development and Deployment
- Resources and tutorials

T[here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) are few README cheatsheets. One example being here, but use your preferred one.
