### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by AlexaH88** [bezebee/star-wars-hackathon#55]
**game.py**
- [x]  class Main
   - [x] handle events
   - [x] update players
   - [x] update countdown
   - [x] run

**display.py**
- [x] class Display
   - [x]  screen
   - [x]  background image
   - [x]  fonts
   - [ ]  fps
   - [ ]  colors

**player.py**
- [x] class Player
   - [x] move (to be split up more)
   - [x] attack 
- [x] class HealthBar
   - [x] draw
- [x] class Sprite
   - [x] load sprites
   - [x] animation 

**soundmanager.py**
- [x] class SoundManager
   - [x] background music
   - [x] luke attack
   - [x] darth attack

**Comment by nils-n** [comment]
Maybe a Game class too that handles the main game loop?

- [ ] class Game

**Comment by AlexaH88** [comment]
Yes, good idea! We've now got a Main class on game.py that Marcello created 😀
